name: Download MSHA Annual Coal Production Zip

on:
  schedule:
    - cron: '0 1 * * *'  # Runs daily at 1:00 AM UTC
  workflow_dispatch:  # Allows manual runs

permissions:
  contents: write  # This gives permission to create releases

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download MSHA Mines ZIP
        run: curl -o annual-coal-production.zip "https://arlweb.msha.gov/OpenGovernmentData/DataSets/MinesProdYearly.zip"

      - name: Upload ZIP File as Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: annual-coal-production.zip
          tag_name: annual-coal-production
          name: "Annual Coal Production ZIP"
          token: ${{ secrets.GITHUB_TOKEN }}
