name: Download MSHA Quarterly Coal Production ZIP File

on:
  schedule:
    - cron: '0 1 * * *'  # Runs daily at 2:00 AM UTC
  workflow_dispatch:  # Allows manual runs

permissions:
  contents: write

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download Quarterly MSHA Coal Production ZIP File
        run: curl -o quarterly-coal-production.zip "https://arlweb.msha.gov/OpenGovernmentData/DataSets/MinesProdQuarterly.zip"

      - name: Upload ZIP File as Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: quarterly-coal-production.zip
          tag_name: quarterly-coal-production  # Unique tag
          name: "MSHA Quarterly Coal Production ZIP File"
          token: ${{ secrets.GITHUB_TOKEN }}
